services:
  - type: web
    name: HyMetDash
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port 10000 --server.enableCORS false"
    plan: free
    region: frankfurt
    branch: master
    autoDeploy: true
