services:
  - type: web
    name: HyMetDash
    env: python
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: RENDER
        value: "true"
    plan: free
